server {
    listen       8888;
    server_name  localhost;
    gzip  on;
    # 设置缓冲区大小
    gzip_buffers 4 16k;
     
    #压缩级别官网建议是6
    gzip_comp_level 6;
    #压缩的类型
    gzip_types text/plain application/javascript text/css application/xml text/javascript application/x-httpd-php;

    #error Connection timed out and 504 error
    large_client_header_buffers 4 16k;
    client_max_body_size 30m;
    client_body_buffer_size 128k;
    fastcgi_connect_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers   4 32k;
    fastcgi_busy_buffers_size 64k;
    fastcgi_temp_file_write_size 64k;

    # worker_processes 8;
    # worker_cpu_affinity 00000001 00000010 00000100 00001000 00010000 00100000 01000000 10000000;
    #扩充最大连接数
    # worker_rlimit_nofile 65535;


    # charset koi8-r;
    # access_log  /var/log/nginx/host.access.log  main;
    # error_log  /var/log/nginx/error.log  error;
	
	location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    location /pms/ {
        rewrite ^.+pms/(.*)$ /$1 break;
        # proxy_pass http://las-gateway.xqxy-js.svc.cluster.local:9999;
        proxy_pass http://10.10.0.101:32257;
    }
    location /api/ {
        rewrite ^.+api/(.*)$ /$1 break;
        # proxy_pass http://las-gateway.xqxy-js.svc.cluster.local:9999;
        proxy_pass http://10.10.0.101:32257;
    }
     location /permission/ {
        rewrite ^.+permission/(.*)$ /$1 break;
        proxy_pass http://10.10.0.101:32257;
    }
    location /RS/ {
        proxy_pass http://10.10.0.101:32257;
        proxy_redirect off;
        proxy_set_header host $host;
        proxy_set_header X-Real-IP      $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # location /rp-fcst/ {
    #   rewrite ^.+rp-fcst/(.*)$ /$1 break;
    #   proxy_pass http://rp-fcst.xqxy.svc.cluster.local:8699;
    #   proxy_redirect off;
    #   proxy_set_header host $host;
    #   proxy_set_header X-Real-IP      $remote_addr;
    #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }
    # location /demo/ {
    #   # rewrite ^.+demo/(.*)$ /$1 break;
    #   # proxy_pass http://demo.xqxy.svc.cluster.local:8080;
    #   # proxy_redirect off;
    #   # proxy_set_header host $host;
    #   # proxy_set_header X-Real-IP      $remote_addr;
    #   # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #   deny all;
    # }
  
    # location /las/ {
    #   proxy_set_header Host $host:$server_port;
    #   proxy_set_header X-Real-IP        $remote_addr;
    #   proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
    #   proxy_pass http://las-nginx.xqxy.svc.cluster.local/las/;
    # }


    error_page  404              /index.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
